### ISSUE TITLE
Implement FDDP

### ISSUE THREAD

**Issue by ManifoldFR** [Simple-Robotics/aligator#18]
The idea is to re-implement the FDDP (_feasible DDP_) algorithm from Crocoddyl, and use it for fair comparison to proxddp.

**Todo list**

- [ ] Basic `Results` struct, with only xs, us, gains and feasibilities
- [ ] Basic `Workspace` struct, with only the per-stage feasibility gaps
- [ ] The FDDP linesearch (with directional derivative accounting for feasibility gaps)
- [ ] The FDDP nonlinear rollout
