### ISSUE TITLE
Public release

### ISSUE THREAD

**Issue by ManifoldFR** [Simple-Robotics/aligator#83]
# Public release

## TO-DO LIST

Related to #82 

### Core

- [x] change CMake project `aligator` #92 
- [x] change includes to `aligator` #92 
- [x] rename macros and preprocessor definitions prefixed by `PROXDDP_` to `ALIGATOR_` #91 
- [x] change namespace to `aligator`
- [x] #84
- [x] Cleanup CMakeLists.txt

### Meta

- [x] change default branch
- [x] add license
- [x] fix CI to use GitHub CI
- [x] conda packaging
- [x] add changelog
- [x] add contributors to README
- [x] standardize pre-commit
- [x] change project name on GitHub
- [x] update README

### Bindings

- [x] #88
- [x] change module name from `proxddp` to `aligator` #93 
- [x] #87
